spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: phuonglam1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: ${JWT_SIGNER_KEY:uGn1btxMAz77FBExhcThICMJpEWG4fwLu6pJiwlObSIubo7ivat3KSD54PRN0467}
  valid-duration: ${JWT_VALID_DURATION:180} # seconds
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:864000} # seconds
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    com.iuh.service.impl.UserServiceImpl: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
openapi:
  service:
    title: Bookstore API documentation
    version: 1.0.0
    description: API for managing books in a bookstore
    server: http://localhost:${server.port}${server.servlet.context-path}
    api-docs: bookstore-api